(() => {
  'use strict';

  const TAU = Math.PI * 2;
  const clamp = (v, a = 0, b = 1) => Math.min(b, Math.max(a, v));
  const lerp = (a, b, t) => a + (b - a) * t;
  const smooth = t => { t = clamp(t); return t * t * (3 - 2 * t); };
  const deg = d => d * Math.PI / 180;

  class Spring {
    constructor(value = 0, frequency = 6, damping = .9) { this.value=value; this.target=value; this.velocity=0; this.frequency=frequency; this.damping=damping; }
    snap(v){ this.value=this.target=v; this.velocity=0; }
    set(v){ this.target=v; }
    step(dt){ dt=clamp(dt||0,0,.04); const w=TAU*this.frequency,k=w*w,c=2*this.damping*w,den=1+dt*c+dt*dt*k; this.velocity=(this.velocity+dt*k*(this.target-this.value))/den; this.value+=dt*this.velocity; if(!Number.isFinite(this.value)||!Number.isFinite(this.velocity))this.snap(this.target); return this.value; }
  }

  const EMOTIONS = {
    neutral:{label:'기본',eyes:['E01','E02'],brows:['B01','B02'],mouth:'M01',arms:'down',legs:'straight',pose:{},gesture:'settle'},
    happy:{label:'행복',eyes:['E03','E04'],brows:['B03','B04'],mouth:'M02',arms:'open',legs:'straight',pose:{headAngle:-1.5,armL:-4,armR:4,blush:.25,energy:.45},gesture:'happy'},
    excited:{label:'신남',eyes:['E11','E12'],brows:['B03','B04'],mouth:'M05',arms:'raised',legs:'straight',pose:{headAngle:1.5,armL:-6,armR:6,legL:-3,legR:3,energy:1},gesture:'bounce'},
    teasing:{label:'장난',eyes:['E01','E04'],brows:['B05','B06'],mouth:'M08',arms:'oneRaised',legs:'bentLeft',pose:{headAngle:-4,headTurn:.08,bodyLean:-2,energy:.55},gesture:'tease'},
    pleading:{label:'울망',eyes:['E09','E10'],brows:['B03','B04'],mouth:'M07',arms:'clasped',legs:'straight',pose:{headAngle:3.5,bodyLean:1,blush:.15,energy:.12},gesture:'plead'},
    relaxed:{label:'느긋',eyes:['E05','E06'],brows:['B01','B02'],mouth:'M02',arms:'down',legs:'straight',pose:{headAngle:-2.5,headTurn:-.05,bodyLean:1.2,energy:.05},gesture:'slow'},
    sick:{label:'아픔',eyes:['E05','E06'],brows:['B03','B04'],mouth:'M07',arms:'down',legs:'straight',pose:{headAngle:4.5,bodyLean:2.2,bodySquash:.02,energy:.02},gesture:'sick'},
    angry:{label:'화남',eyes:['E07','E08'],brows:['B05','B06'],mouth:'M07',arms:'crossed',legs:'straight',pose:{headAngle:-1,bodyLean:-2,energy:.85},gesture:'angry'},
    annoyed:{label:'삐짐',eyes:['E05','E06'],brows:['B05','B06'],mouth:'M07',arms:'crossed',legs:'straight',pose:{headAngle:-5,headTurn:-.08,bodyLean:1.5,energy:.12},gesture:'huff'},
    sad:{label:'슬픔',eyes:['E09','E10'],brows:['B03','B04'],mouth:'M07',arms:'down',legs:'straight',pose:{headAngle:5,bodyLean:1.4,energy:.03},gesture:'sad'},
    surprised:{label:'놀람',eyes:['E11','E12'],brows:['B03','B04'],mouth:'M06',arms:'palms',legs:'straight',pose:{bodySquash:-.02,energy:.85},gesture:'startle'},
    embarrassed:{label:'부끄러움',eyes:['E03','E04'],brows:['B03','B04'],mouth:'M03',arms:'cheek',legs:'straight',pose:{headAngle:3,headTurn:.06,blush:1,energy:.18},gesture:'shy'},
    scared:{label:'겁남',eyes:['E11','E12'],brows:['B03','B04'],mouth:'M06',arms:'clasped',legs:'straight',pose:{headAngle:2,bodySquash:.025,energy:.72},gesture:'shiver'},
    smug:{label:'의기양양',eyes:['E05','E06'],brows:['B05','B06'],mouth:'M02',arms:'crossed',legs:'straight',pose:{headAngle:-4.5,headTurn:.08,bodyLean:-1.2,energy:.22},gesture:'smug'},
    confused:{label:'갸웃',eyes:['E01','E06'],brows:['B03','B06'],mouth:'M01',arms:'cheek',legs:'straight',pose:{headAngle:7,headTurn:-.05,energy:.2},gesture:'tilt'},
    love:{label:'좋아!',eyes:['E13','E14'],brows:['B03','B04'],mouth:'M02',arms:'clasped',legs:'straight',pose:{headAngle:-2,blush:.55,energy:.72},gesture:'love'}
  };

  const DEFAULTS={headAngle:0,headTurn:0,bodyLean:0,bodySquash:0,armL:0,armR:0,legL:0,legR:0,energy:.1,blush:0};

  class MotionController {
    constructor(config){ this.config=config; this.springs={}; for(const[k,v]of Object.entries(DEFAULTS)){const slow=k.startsWith('arm')||k.startsWith('leg')||k==='bodyLean';this.springs[k]=new Spring(v,slow?4.5:6.2,.9);} this.emotion='neutral';this.previousEmotion='neutral';this.changedAt=performance.now();this.gestureStarted=this.changedAt;this.manualMouth=0;this.testLipSync=false;this.micActive=false;this.micLevel=0;this.blinkOpen=1;this.blinkStart=-1;this.nextBlink=performance.now()+2800;this.nextIdleTurn=performance.now()+4200;this.idleReturnAt=0;this.idleTurn=new Spring(0,1.6,.95);this.idleTilt=new Spring(0,1.4,.95);this.seed=0x51a17;this.applyEmotion('neutral',true); }
    rand(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;}
    applyEmotion(id,snap=false){if(!EMOTIONS[id])id='neutral';this.previousEmotion=this.emotion;this.emotion=id;this.changedAt=performance.now();this.gestureStarted=this.changedAt;const pose={...DEFAULTS,...(EMOTIONS[id].pose||{})};for(const[k,s]of Object.entries(this.springs))snap?s.snap(pose[k]??0):s.set(pose[k]??0);}
    setManualMouth(v){this.manualMouth=clamp(Number(v)||0);} setLipTest(v){this.testLipSync=!!v;} setMicLevel(v){this.micLevel=clamp(v);} setMicActive(v){this.micActive=!!v;} forceBlink(){this.blinkStart=performance.now();}
    updateBlink(now,forceQa=false){if(this.blinkStart<0&&now>=this.nextBlink&&!forceQa)this.blinkStart=now;if(this.blinkStart<0){this.blinkOpen=1;return;}const d=this.config.idle.blinkDurationMs||180,q=(now-this.blinkStart)/d;if(q<.36)this.blinkOpen=1-smooth(q/.36);else if(q<.58)this.blinkOpen=0;else if(q<1)this.blinkOpen=smooth((q-.58)/.42);else{this.blinkOpen=1;this.blinkStart=-1;this.nextBlink=now+lerp(this.config.idle.blinkMinMs,this.config.idle.blinkMaxMs,this.rand());}}
    updateIdle(now,dt,qa=false){if(!qa&&now>=this.nextIdleTurn){this.idleTurn.set(lerp(-.11,.11,this.rand()));this.idleTilt.set(lerp(-2.1,2.1,this.rand()));this.idleReturnAt=now+lerp(1100,2200,this.rand());this.nextIdleTurn=now+lerp(this.config.idle.headTurnMinMs,this.config.idle.headTurnMaxMs,this.rand());}if(this.idleReturnAt&&now>=this.idleReturnAt){this.idleTurn.set(0);this.idleTilt.set(0);this.idleReturnAt=0;}if(qa){this.idleTurn.set(0);this.idleTilt.set(0);}this.idleTurn.step(dt);this.idleTilt.step(dt);}
    lipTarget(sec){if(this.micActive)return this.micLevel;if(this.testLipSync){const phrase=sec%4.1;if(phrase>3.2)return 0;const env=smooth(Math.min(1,phrase*5))*smooth(Math.min(1,(3.2-phrase)*4));return clamp((Math.abs(Math.sin(sec*9.4))*.56+Math.abs(Math.sin(sec*14.1+.7))*.34+.05)*env);}return this.manualMouth;}
    gesture(now){const kind=EMOTIONS[this.emotion].gesture,t=(now-this.gestureStarted)/1000,one=d=>Math.sin(Math.PI*clamp(t/d));switch(kind){case'happy':return{bob:Math.sin(t*7.5)*1.7*Math.exp(-t*1.3)};case'bounce':return{bob:-Math.abs(Math.sin(t*7.8))*10*Math.exp(-t*.45),squash:Math.sin(t*7.8)*.018*Math.exp(-t*.5),leg:Math.sin(t*7.8)*3};case'tease':return{sway:-one(.7)*2.5,armR:one(.7)*4};case'plead':return{bob:Math.sin(t*3.6)*.7,arms:Math.sin(t*3.1)*1.2};case'sick':return{sway:Math.sin(t*1.9)*1.1,bob:1.2};case'angry':return{shake:Math.sin(t*34)*1.6*Math.exp(-t*1.2)};case'huff':return{sway:-1.5+Math.sin(t*1.6)*.35};case'sad':return{bob:1.5+Math.sin(t*1.3)*.4};case'startle':return{bob:-one(.38)*15,squash:-one(.38)*.04,arms:one(.45)*4};case'shy':return{sway:Math.sin(t*2)*.8};case'shiver':return{shake:Math.sin(t*30)*1.2};case'smug':return{sway:-.6+Math.sin(t*1.1)*.25};case'tilt':return{sway:Math.sin(t*1.2)*.25};case'love':return{bob:-Math.abs(Math.sin(t*3.8))*3.2*Math.exp(-t*.25),arms:Math.sin(t*3.8)*1.2};default:return{};}}
    update(now,dt,qa=false){this.updateBlink(now,qa);this.updateIdle(now,dt,qa);const sec=now/1000,g=this.gesture(now),out={};for(const[k,s]of Object.entries(this.springs))out[k]=s.step(dt);out.headTurn+=this.idleTurn.value;out.headAngle+=this.idleTilt.value;out.bodyLean+=g.sway||0;out.bodySquash+=g.squash||0;out.armL+=(g.arms||0)+(g.armL||0);out.armR+=(g.arms||0)+(g.armR||0);out.legL+=g.leg||0;out.legR-=g.leg||0;out.globalX=g.shake||0;out.globalBob=(g.bob||0)+Math.sin(sec*1.55)*.45*(.25+out.energy);out.breath=Math.sin(sec*TAU*(this.config.idle.breathHz||.22));out.blinkOpen=this.blinkOpen;out.mouthOpen=this.lipTarget(sec);out.transition=smooth((now-this.changedAt)/(this.config.motion.transitionMs||420));out.emotion=this.emotion;out.previousEmotion=this.previousEmotion;return out;}
  }

  class PartAtlasRenderer {
    constructor(canvas,fxCanvas,config){this.canvas=canvas;this.fxCanvas=fxCanvas;this.config=config;this.ctx=canvas.getContext('2d',{alpha:true});this.fx=fxCanvas.getContext('2d',{alpha:true});this.images={};this.debug=false;this.label='Sprite parts + micro-mesh';this.partSnapshot={};this.lastMouthSprite='M01';this.lastEyeSprite='E01/E02';this.lastArmPose='down';this.lastLegPose='straight';const[w,h]=config.canvas;canvas.width=w;canvas.height=h;fxCanvas.width=w;fxCanvas.height=h;}
    async load(){await Promise.all(Object.entries(this.config.sheets).map(async([id,url])=>{const img=new Image();img.decoding='async';img.src=url;await img.decode();this.images[id]=img;}));return true;}
    part(id){return this.config.parts[id];}
    draw(id,opt={}){const p=this.part(id);if(!p)return;const img=this.images[String(p.sheet)];if(!img)return;const[sx,sy,sw,sh]=p.src,center=opt.center||this.config.layout[id]?.center||[0,0],scale=opt.scale??this.config.layout[id]?.scale??1,scaleX=opt.scaleX??1,scaleY=opt.scaleY??1,alpha=opt.alpha??1;if(alpha<=.001)return;const angle=opt.angle??this.config.layout[id]?.angle??0,flipX=opt.flipX?-1:1,dw=sw*scale*scaleX,dh=sh*scale*scaleY,c=this.ctx;c.save();c.globalAlpha*=alpha;c.translate(center[0],center[1]);c.rotate(deg(angle));c.scale(flipX,1);c.drawImage(img,sx,sy,sw,sh,-dw/2,-dh/2,dw,dh);if(this.debug){c.strokeStyle='rgba(255,90,170,.75)';c.lineWidth=1.2;c.strokeRect(-dw/2,-dh/2,dw,dh);c.fillStyle='#fff';c.font='10px monospace';c.fillText(id,-dw/2+2,-dh/2+11);}c.restore();}
    drawWarped(id,opt={}){const p=this.part(id);if(!p)return;const img=this.images[String(p.sheet)];if(!img)return;const[sx,sy,sw,sh]=p.src,center=opt.center||this.config.layout[id]?.center||[0,0],scale=opt.scale??this.config.layout[id]?.scale??1,alpha=opt.alpha??1,shear=opt.shear||0,bulge=opt.bulge||0,strips=10,baseW=sw*scale,baseH=sh*scale,top=center[1]-baseH/2,c=this.ctx;c.save();c.globalAlpha*=alpha;for(let i=0;i<strips;i++){const t=(i+.5)/strips,sy0=sy+sh*i/strips,ssh=sh/strips+1,dh=baseH/strips+1,y=top+baseH*i/strips,w=baseW*(1+bulge*Math.sin(Math.PI*t)),x=center[0]-w/2+shear*(t-.5);c.drawImage(img,sx,sy0,sw,ssh,x,y,w,dh);}c.restore();}
    withGroup(pivot,translate,angle,scaleX,scaleY,fn){const c=this.ctx;c.save();c.translate(pivot[0]+translate[0],pivot[1]+translate[1]);c.rotate(deg(angle));c.scale(scaleX,scaleY);c.translate(-pivot[0],-pivot[1]);fn();c.restore();}
    eyePair(def,alpha=1,blinkOpen=1){const[l,r]=def.eyes,L=this.config.layout.eyeLeft,R=this.config.layout.eyeRight,turn=this._p.headTurn||0,lx=L.center[0]+turn*12,rx=R.center[0]+turn*12,openA=alpha*blinkOpen,closedA=alpha*(1-blinkOpen),ls=this.config.eyeScale[l]||L.scale,rs=this.config.eyeScale[r]||R.scale;if(openA>.002){this.draw(l,{center:[lx,L.center[1]],scale:ls,alpha:openA});this.draw(r,{center:[rx,R.center[1]],scale:rs,alpha:openA});}if(closedA>.002){this.draw('E03',{center:[lx,L.center[1]],scale:this.config.eyeScale.E03,alpha:closedA});this.draw('E04',{center:[rx,R.center[1]],scale:this.config.eyeScale.E04,alpha:closedA});}}
    browPair(def,alpha=1){const[l,r]=def.brows,L=this.config.layout.browLeft,R=this.config.layout.browRight,turn=this._p.headTurn||0;this.draw(l,{center:[L.center[0]+turn*10,L.center[1]],scale:this.config.browScale[l]||L.scale,alpha});this.draw(r,{center:[R.center[0]+turn*10,R.center[1]],scale:this.config.browScale[r]||R.scale,alpha});}
    drawMouthBase(id,alpha){const L=this.config.layout.mouth,turn=this._p.headTurn||0;this.draw(id,{center:[L.center[0]+turn*9,L.center[1]],scale:this.config.mouthScale[id]||.5,alpha});}
    drawLipSync(level){const L=this.config.layout.mouth,x=L.center[0]+(this._p.headTurn||0)*9,y=L.center[1];if(level<.02)return false;let a='M03',b='M04',t=0;if(level<.48){t=clamp((level-.02)/.46);}else{t=clamp((level-.48)/.52);a='M04';b='M05';}const e=smooth(t);this.draw(a,{center:[x,y],scale:this.config.mouthScale[a],alpha:1-e});this.draw(b,{center:[x,y],scale:this.config.mouthScale[b],alpha:e});this.lastMouthSprite=e<.5?a:b;return true;}
    drawArmPose(pose,alpha=1,side={l:0,r:0}){const lo=this.config.layout,drawPair=(l,r,lp,rp)=>{this.draw(l,{center:lp.center,scale:lp.scale,angle:(lp.angle||0)+side.l,alpha});this.draw(r,{center:rp.center,scale:rp.scale,angle:(rp.angle||0)+side.r,alpha});};if(pose==='down')drawPair('A01','A02',lo.armNeutralLeft,lo.armNeutralRight);else if(pose==='open')drawPair('A03','A04',lo.armOpenLeft,lo.armOpenRight);else if(pose==='raised')drawPair('A05','A06',lo.armRaisedLeft,lo.armRaisedRight);else if(pose==='oneRaised'){this.draw('A01',{center:lo.armNeutralLeft.center,scale:lo.armNeutralLeft.scale,angle:(lo.armNeutralLeft.angle||0)+side.l,alpha});this.draw('A06',{center:lo.armRaisedRight.center,scale:lo.armRaisedRight.scale,angle:(lo.armRaisedRight.angle||0)+side.r,alpha});}else{const map={crossed:'A07',cheek:'A08',palms:'A09',clasped:'A10'},id=map[pose]||'A07',offsets={crossed:[300,460,.95],cheek:[306,452,1.02],palms:[300,458,1.02],clasped:[300,454,.98]},[x,y,s]=offsets[pose]||offsets.crossed;this.draw(id,{center:[x,y],scale:s,alpha});}}
    drawLegs(pose,alpha=1){const lo=this.config.layout,p=this._p;if(pose==='bentLeft'){this.draw('L07',{center:[247,687],scale:.96,angle:-4+(p.legL||0),alpha});this.draw('L03',{center:lo.legRight.center,scale:lo.legRight.scale,angle:p.legR||0,alpha});this.draw('L04',{center:[230,825],scale:lo.shoeLeft.scale,angle:-7+(p.legL||0),alpha});this.draw('L05',{center:lo.shoeRight.center,scale:lo.shoeRight.scale,angle:p.legR||0,alpha});}else{this.draw('L02',{center:lo.legLeft.center,scale:lo.legLeft.scale,angle:p.legL||0,alpha});this.draw('L03',{center:lo.legRight.center,scale:lo.legRight.scale,angle:p.legR||0,alpha});this.draw('L04',{center:lo.shoeLeft.center,scale:lo.shoeLeft.scale,angle:(p.legL||0)*.65,alpha});this.draw('L05',{center:lo.shoeRight.center,scale:lo.shoeRight.scale,angle:(p.legR||0)*.65,alpha});}}
    render(p,emotion){this._p=p;const c=this.ctx,fx=this.fx,[w,h]=this.config.canvas;c.clearRect(0,0,w,h);fx.clearRect(0,0,w,h);const cur=EMOTIONS[emotion]||EMOTIONS.neutral,prev=EMOTIONS[p.previousEmotion]||cur,t=p.transition,gx=p.globalX||0,gy=p.globalBob||0;this.withGroup([300,607],[gx,gy],p.bodyLean*.15,1,1,()=>{if(prev.legs!==cur.legs&&t<.999){this.drawLegs(prev.legs,1-t);this.drawLegs(cur.legs,t);}else this.drawLegs(cur.legs,1);});const breath=p.breath*.008,squash=p.bodySquash||0;this.withGroup([300,365],[gx,gy],p.bodyLean,1+squash*.18,1-squash*.18,()=>{this.drawWarped('T01',{center:this.config.layout.T01.center,scale:this.config.layout.T01.scale,shear:p.bodyLean*.45,bulge:breath});this.drawWarped('L01',{center:this.config.layout.L01.center,scale:this.config.layout.L01.scale,shear:p.bodyLean*.7,bulge:breath*.65});this.draw('T02');this.draw('T03');this.draw('T04');if(prev.arms!==cur.arms&&t<.999){this.drawArmPose(prev.arms,1-t,{l:p.armL,r:p.armR});this.drawArmPose(cur.arms,t,{l:p.armL,r:p.armR});}else this.drawArmPose(cur.arms,1,{l:p.armL,r:p.armR});});const hp=this.config.layout.head.pivot,headX=(p.headTurn||0)*12;this.withGroup(hp,[gx+headX,gy],p.headAngle,1-Math.abs(p.headTurn||0)*.025,1,()=>{const follow=(p.headAngle*.28)+(p.bodyLean*.12)+Math.sin(performance.now()/470)*.6*(.25+p.energy);this.draw('H03',{center:this.config.layout.H03.center,scale:this.config.layout.H03.scale,angle:-follow});this.draw('H04',{center:this.config.layout.H04.center,scale:this.config.layout.H04.scale,angle:follow});this.draw('H01');this.draw('F01');this.draw('H02');if(prev!==cur&&t<.999){this.browPair(prev,1-t);this.browPair(cur,t);this.eyePair(prev,1-t,p.blinkOpen);this.eyePair(cur,t,p.blinkOpen);}else{this.browPair(cur,1);this.eyePair(cur,1,p.blinkOpen);}if(!this.drawLipSync(p.mouthOpen)){if(prev.mouth!==cur.mouth&&t<.999){this.drawMouthBase(prev.mouth,1-t);this.drawMouthBase(cur.mouth,t);}else this.drawMouthBase(cur.mouth,1);this.lastMouthSprite=cur.mouth;}const blush=clamp(p.blush||0);if(blush>.01){this.draw('F02',{center:[225,298],scale:.42,alpha:blush*.55});this.draw('F03',{center:[375,298],scale:.42,alpha:blush*.55});}this.draw('H05');this.draw('H06');});this.lastEyeSprite=`${cur.eyes[0]}/${cur.eyes[1]}${p.blinkOpen<.5?' -> E03/E04':''}`;this.lastArmPose=cur.arms;this.lastLegPose=cur.legs;this.partSnapshot={eyes:this.lastEyeSprite,mouth:this.lastMouthSprite,arms:cur.arms,legs:cur.legs,blinkOpen:+p.blinkOpen.toFixed(3),mouthOpen:+p.mouthOpen.toFixed(3)};}
    meshHealth(){return{mode:'sprite-parts+micro-mesh',inverted:0,degenerate:0,activeParts:58};}
  }

  window.JiraiRig={Spring,MotionController,PartAtlasRenderer,EMOTIONS};
})();
