from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "assets/runtime/jirai_runtime_atlas_v0.json"
EMOTIONS = ROOT / "config/emotions_v0.json"
OUT = ROOT / "firmware/generated/jirai_runtime_table.h"


def c_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").upper()


def q8(value: float) -> int:
    return int(round(value * 256.0))


def main() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    emotion_doc = json.loads(EMOTIONS.read_text(encoding="utf-8"))
    rects = manifest["rects"]
    asset_names = list(rects.keys())
    asset_ids = {name: index for index, name in enumerate(asset_names)}

    lines: list[str] = []
    lines += [
        "// Auto-generated by tools/generate_firmware_tables.py. Do not edit manually.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define JIRAI_ATLAS_WIDTH {manifest['size'][0]}",
        f"#define JIRAI_ATLAS_HEIGHT {manifest['size'][1]}",
        f"#define JIRAI_ASSET_COUNT {len(asset_names)}",
        f"#define JIRAI_EMOTION_COUNT {len(emotion_doc['states'])}",
        "",
        "typedef struct { uint16_t x, y, w, h; } JiraiAssetRect;",
        "typedef struct {",
        "    uint8_t eye_asset;",
        "    uint8_t brow_asset;",
        "    uint8_t mouth_asset;",
        "    int16_t head_rotation_q8;",
        "    int16_t body_y_q8;",
        "    uint16_t body_scale_y_q8;",
        "    uint16_t breath_q8;",
        "    uint16_t mouth_open_q8;",
        "} JiraiEmotionState;",
        "",
        "typedef enum {",
    ]

    for index, name in enumerate(asset_names):
        lines.append(f"    JIRAI_ASSET_{c_name(name)} = {index},")
    lines += ["} JiraiAssetId;", "", "static const JiraiAssetRect kJiraiAssetRects[JIRAI_ASSET_COUNT] = {"]
    for name in asset_names:
        x, y, w, h = rects[name]
        lines.append(f"    /* {name} */ {{ {x}, {y}, {w}, {h} }},")
    lines += ["};", "", "typedef enum {"]

    emotion_names = list(emotion_doc["states"].keys())
    for index, name in enumerate(emotion_names):
        lines.append(f"    JIRAI_EMOTION_{c_name(name)} = {index},")
    lines += ["} JiraiEmotionId;", "", "static const JiraiEmotionState kJiraiEmotionStates[JIRAI_EMOTION_COUNT] = {"]

    fallback = asset_ids.get("mouth_closed", 0)
    for name in emotion_names:
        state = emotion_doc["states"][name]
        eye = asset_ids.get(state["eye"], 0)
        brow = asset_ids.get(state["brow"], 0)
        mouth = asset_ids.get(state["mouth"], fallback)
        lines.append(
            "    /* %s */ { %d, %d, %d, %d, %d, %d, %d, %d }," % (
                name,
                eye,
                brow,
                mouth,
                q8(state.get("head_rotation_deg", 0.0)),
                q8(state.get("body_y", 0.0)),
                q8(state.get("body_scale_y", 1.0)),
                q8(state.get("breath", 1.0)),
                q8(state.get("mouth_open_y", 0.0)),
            )
        )
    lines += ["};", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUT.relative_to(ROOT)} with {len(asset_names)} assets and {len(emotion_names)} emotions")


if __name__ == "__main__":
    main()
